# 로컬 개발용 DB Docker Compose
version: '3.7'
services:
  pg:
    image: postgres:16.2-alpine
    restart: always
    environment:
      - 'POSTGRES_PASSWORD=dorabangs!'
      - 'POSTGRES_DB=dorabangs'
      - 'TZ=Asia/Seoul'
    ports:
      - '5432:5432'
    networks:
      - dorabangs
networks:
  dorabangs:
    driver: bridge
