version: '3.7'
services:
  pg:
    image: postgres:16.2-alpine
    restart: unless-stopped
    environment:
      - 'POSTGRES_PASSWORD=linkit1234!'
      - 'POSTGRES_DB=linkit'
      - 'TZ=Asia/Seoul'
    ports:
      - '5432:5432'
    networks:
      - linkit
    volumes:
      - linkit-data:/var/lib/postgresql/data
networks:
  linkit:
    driver: bridge
volumes:
  linkit-data:
    external: false
