service: dorabangs-node
plugins:
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-2
  architecture: arm64
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'sqs:ReceiveMessage'
        - 'sqs:SendMessage'
        - 'sqs:DeleteMessage'
      Resource: '*'

custom:
  dotenv:
    basePath: ./
  optimize:
    external: ['swagger-ui-dist']

functions:
  server:
    handler: dist/index.handler
    timeout: 30
    events:
      - http:
          method: any
          path: '/'
          cors:
            origin: '*'
      - http:
          method: any
          path: '{proxy+}'
          cors:
            origin: '*'
  aiWorker:
    handler: worker-dist/index.handler
    timeout: 600
    description: AI Classification Async Worker
    events:
      - sqs:
          arn:
            Fn::GetAtt: [AIEventQueue, Arn]
          maximumConcurrency: 5

package:
  exclude:
    - '**/*'
  include:
    - 'dist/**'
    - 'worker-dist/**'

resources:
  Resources:
    AIEventQueue:
      Type: 'AWS::SQS::Queue'
      Properties:
        QueueName: 'ai-event-queue.fifo'
        FifoQueue: true
        ContentBasedDeduplication: true
        VisibilityTimeout: 600
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt:
              - 'AIEventDeadQueue'
              - 'Arn'
          maxReceiveCount: 1
    AIEventDeadQueue:
      Type: 'AWS::SQS::Queue'
      Properties:
        FifoQueue: true
        QueueName: 'ai-event-dead-queue.fifo'
